# Generated by Django 4.1.5 on 2023-01-20 09:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geouser",
            name="adress1",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="geouser",
            name="adress2",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="geouser",
            name="company_name",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="geouser",
            name="licenced_surveyors",
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="geouser",
            name="nip_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="geouser",
            name="regon_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="geouser",
            name="regural_surveyors",
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="geouser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="PL"
            ),
        ),
    ]
