# Generated by Django 4.1.5 on 2023-01-20 09:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_geouser_adress1_geouser_adress2_geouser_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geouser",
            name="company_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="PL"
            ),
        ),
    ]
