# Generated by Django 4.1.5 on 2023-01-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_geouser_company_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geouser",
            name="adress1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="geouser",
            name="adress2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="geouser",
            name="licenced_surveyors",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="geouser",
            name="nip_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="geouser",
            name="regon_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="geouser",
            name="regural_surveyors",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
