version: '3.9'
services:
  web:
    build:
      context: ..
      dockerfile: ./.docker/dockerfile
    volumes:
      - C:/Devs/GeoDocGenerator/geo_doc_generator:/app/geo_doc_generator/
    ports:
      - "8000:8000"
