services:
  geo-doc:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ../geo_doc_generator:/app/geo_doc_generator/
    ports:
      - "8000:8000"
