version: '3.9'
services:
  web:
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DEV=${DEV}
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ../geo_doc_generator:/app/geo_doc_generator/
    ports:
      - "8000:8000"
