# Generated by Django 4.1.5 on 2023-02-04 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeodeticWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_work",
                    models.CharField(
                        default="XX.6640.XXXX.RRRR",
                        max_length=25,
                        verbose_name="identyfikator pracy",
                    ),
                ),
                (
                    "voivodeship",
                    models.CharField(
                        default="zachodniopomorskie",
                        max_length=50,
                        null=True,
                        verbose_name="województwo",
                    ),
                ),
                (
                    "county",
                    models.CharField(max_length=50, null=True, verbose_name="powiat"),
                ),
                (
                    "commune",
                    models.CharField(max_length=50, null=True, verbose_name="gmina"),
                ),
                (
                    "precinct",
                    models.CharField(max_length=50, null=True, verbose_name="obręb"),
                ),
                (
                    "work_object",
                    models.CharField(max_length=100, null=True, verbose_name="obiekt"),
                ),
                (
                    "plots",
                    models.CharField(max_length=50, null=True, verbose_name="działki"),
                ),
                (
                    "work_scope",
                    models.CharField(
                        max_length=100, null=True, verbose_name="cel pracy"
                    ),
                ),
                (
                    "survey_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="data pomiaru",
                    ),
                ),
                (
                    "begin_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="data rozpoczęcia",
                    ),
                ),
                (
                    "area",
                    models.CharField(max_length=10, null=True, verbose_name="obszar"),
                ),
                (
                    "change_bdot_database",
                    models.BooleanField(
                        default=False, null=True, verbose_name="zmiana BDOT500"
                    ),
                ),
                (
                    "change_gesut_database",
                    models.BooleanField(
                        default=False, null=True, verbose_name="zmiana GESUT"
                    ),
                ),
                (
                    "change_egib_database",
                    models.BooleanField(
                        default=False, null=True, verbose_name="zmiana EGiB"
                    ),
                ),
                (
                    "documentation_date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="data dokumentacji",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INP", "W trakcie"),
                            ("END", "Zakończona"),
                            ("CAN", "Anulowana"),
                        ],
                        default="INP",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        default=1,
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="static/geodetic_work/"
                    ),
                ),
                (
                    "source_data",
                    models.TextField(
                        default="Po analizie materiałów pozyskanych z PZGiK do...",
                        verbose_name="dane źródłowe",
                    ),
                ),
                (
                    "comparision_description",
                    models.TextField(
                        default="Wykonano porównanie mapy...",
                        verbose_name="wywiad terenowy:",
                    ),
                ),
                (
                    "geodetic_network_description",
                    models.TextField(
                        default="Założono osnowę pomiarową ...",
                        verbose_name="opis osnowy geodezyjnej",
                    ),
                ),
                (
                    "control_survey_description",
                    models.TextField(
                        default="Wykonano pomiar kontrolny ...",
                        verbose_name="opis pomiaru kontrolnego",
                    ),
                ),
                (
                    "land_survey_descrption",
                    models.TextField(
                        default="Wykonano pomiar systuacyjny metodą ...",
                        verbose_name="opis pomiaru",
                    ),
                ),
                (
                    "results_descrption",
                    models.TextField(
                        default="Wyniki uzyskano w układzie ...",
                        verbose_name="wyniki pomiaru",
                    ),
                ),
                (
                    "zudp_building_permit",
                    models.TextField(
                        default="ZUD i pozwolenie na budowe ..",
                        verbose_name="ZUD, pozwolenia",
                    ),
                ),
                (
                    "boundary_plots",
                    models.TextField(
                        default="Granice spełniają/nie spełniają ...",
                        verbose_name="informacja o granicach",
                    ),
                ),
                (
                    "output_documents",
                    models.TextField(
                        default="Dla zamawiającego przygotowano...",
                        verbose_name="dokumentacja dla klienta",
                    ),
                ),
                (
                    "update_county_database",
                    models.TextField(
                        default="Przekazno pliki w formacie ...",
                        verbose_name="dane przekazywane do PZGiK",
                    ),
                ),
                (
                    "update_egib_database",
                    models.TextField(
                        default="Kierownik prac stwierdził/nie stwierdził ...",
                        verbose_name="zmiany egib",
                    ),
                ),
                (
                    "id_work",
                    models.OneToOneField(
                        default="XX.6640.XXXX.RRRR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodetic_work.geodeticwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListOfCoordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="static/geodetic_work/"
                    ),
                ),
                (
                    "list_of_coordinates",
                    models.TextField(verbose_name="Wykaz współrzędnych"),
                ),
                (
                    "id_work",
                    models.OneToOneField(
                        default="XX.6640.XXXX.RRRR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodetic_work.geodeticwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeodeticNetworkSurveyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="static/geodetic_work/"
                    ),
                ),
                ("raport", models.TextField(verbose_name="Raport")),
                (
                    "id_work",
                    models.OneToOneField(
                        default="XX.6640.XXXX.RRRR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodetic_work.geodeticwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeodeticNetworkDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="static/geodetic_work/"
                    ),
                ),
                (
                    "id_work",
                    models.OneToOneField(
                        default="XX.6640.XXXX.RRRR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodetic_work.geodeticwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeodeticNetworkCoordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="static/geodetic_work/"
                    ),
                ),
                (
                    "list_of_coordinates",
                    models.TextField(verbose_name="Wykaz współrzędnych"),
                ),
                (
                    "id_work",
                    models.OneToOneField(
                        default="XX.6640.XXXX.RRRR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodetic_work.geodeticwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FieldDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="static/geodetic_work/"
                    ),
                ),
                (
                    "id_work",
                    models.OneToOneField(
                        default="XX.6640.XXXX.RRRR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodetic_work.geodeticwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComaparisionMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="static/geodetic_work/"
                    ),
                ),
                (
                    "id_work",
                    models.OneToOneField(
                        default="XX.6640.XXXX.RRRR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodetic_work.geodeticwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChangeListPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="static/geodetic_work/"
                    ),
                ),
                (
                    "id_work",
                    models.OneToOneField(
                        default="XX.6640.XXXX.RRRR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodetic_work.geodeticwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChangeListBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="static/geodetic_work/"
                    ),
                ),
                (
                    "id_work",
                    models.OneToOneField(
                        default="XX.6640.XXXX.RRRR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodetic_work.geodeticwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
