# Generated by Django 4.1.5 on 2023-02-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geodetic_work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodeticwork",
            name="pdf_documentation",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AlterField(
            model_name="changelistbuilding",
            name="id_work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="geodetic_work.geodeticwork",
            ),
        ),
        migrations.AlterField(
            model_name="changelistplot",
            name="id_work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="geodetic_work.geodeticwork",
            ),
        ),
        migrations.AlterField(
            model_name="comaparisionmap",
            name="id_work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="geodetic_work.geodeticwork",
            ),
        ),
        migrations.AlterField(
            model_name="fielddraft",
            name="id_work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="geodetic_work.geodeticwork",
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworkcoordinates",
            name="id_work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="geodetic_work.geodeticwork",
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworkdraft",
            name="id_work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="geodetic_work.geodeticwork",
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworksurveydata",
            name="id_work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="geodetic_work.geodeticwork",
            ),
        ),
        migrations.AlterField(
            model_name="listofcoordinates",
            name="id_work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="geodetic_work.geodeticwork",
            ),
        ),
        migrations.AlterField(
            model_name="technicaldescription",
            name="id_work",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="geodetic_work.geodeticwork",
            ),
        ),
        migrations.CreateModel(
            name="TableOfContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="static/geodetic_work/"
                    ),
                ),
                (
                    "id_work",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodetic_work.geodeticwork",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
