# Generated by Django 4.2.5 on 2023-09-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodetic_work", "0002_geodeticwork_pdf_documentation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="changelistbuilding",
            name="docx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AddField(
            model_name="changelistplot",
            name="docx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AddField(
            model_name="comaparisionmap",
            name="docx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AddField(
            model_name="fielddraft",
            name="docx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AddField(
            model_name="geodeticnetworkcoordinates",
            name="docx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AddField(
            model_name="geodeticnetworkdraft",
            name="docx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AddField(
            model_name="geodeticnetworksurveydata",
            name="docx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AddField(
            model_name="listofcoordinates",
            name="docx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AddField(
            model_name="tableofcontent",
            name="docx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AddField(
            model_name="technicaldescription",
            name="docx_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
    ]
