# Generated by Django 4.2.5 on 2023-09-23 20:04

from django.db import migrations, models
import geodetic_work.models.document
import geodetic_work.models.geodetic_work


class Migration(migrations.Migration):
    dependencies = [
        ("geodetic_work", "0002_geodeticwork_pdf_documentation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelistbuilding",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="changelistplot",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="comaparisionmap",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="fielddraft",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworkcoordinates",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworkdraft",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworksurveydata",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="geodeticwork",
            name="pdf_documentation",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.geodetic_work.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="geodeticwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("INP", "W trakcie"),
                    ("END", "Zakończona"),
                    ("CAN", "Anulowana"),
                ],
                default="INP",
                max_length=3,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="geodeticwork",
            name="work_scope",
            field=models.CharField(
                choices=[
                    ("MDCP", "sporządzenie mapy do celów projektowych"),
                    (
                        "INW",
                        "geodezyjna inwentaryzacja powykonawcza obiektów budowalnych",
                    ),
                    (
                        "WZNOW",
                        "wznowienie znaków granicznych, wyznaczenie pkt granicznych lub ustalenie przebiegu granic",
                    ),
                    ("MZPPN", "sporządzenie mapy z projektem podziału nieruchomości"),
                    ("PSCPN", "sporządzenie projeku scalenia i podziału nieruchomości"),
                    ("MDCPRAW", "sporządzenie innej mapy do celów prawnych"),
                    ("PSWG", "sporządzenie projektu scalenia lub wymiany gruntów"),
                    (
                        "ROZG",
                        "sporządzenie dokumentacji geodezyjnej na potrzeby rozgranicznenia nieruchomości",
                    ),
                    ("INNE", "wykonanie innych czynności lub dokumentacji geodezyjnej"),
                ],
                default="MDCP",
                max_length=10,
                null=True,
                verbose_name="cel pracy",
            ),
        ),
        migrations.AlterField(
            model_name="listofcoordinates",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="tableofcontent",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="technicaldescription",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
    ]
