# Generated by Django 4.2.5 on 2023-11-02 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geodetic_work", "0003_alter_changelistbuilding_pdf_file_and_more"),
        ("geodetic_work", "0003_changelistbuilding_docx_file_and_more"),
    ]

    operations = []
