# Generated by Django 4.1.5 on 2023-01-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodetic_work", "0003_alter_geodeticwork_contractor"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodeticwork",
            name="area",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="comaparisionmap",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AlterField(
            model_name="fielddraft",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworkcoordinates",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworkdraft",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworksurveydata",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AlterField(
            model_name="listofcoordinates",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
        migrations.AlterField(
            model_name="technicaldescription",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="static/geodetic_work/"
            ),
        ),
    ]
