# Generated by Django 4.2.5 on 2024-07-31 19:21

from django.db import migrations, models
import geodetic_work.models.document


class Migration(migrations.Migration):

    dependencies = [
        ("geodetic_work", "0004_merge_20231102_2058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelistbuilding",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="changelistplot",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="comaparisionmap",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="fielddraft",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworkcoordinates",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworkdraft",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="geodeticnetworksurveydata",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="listofcoordinates",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="tableofcontent",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="technicaldescription",
            name="docx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=geodetic_work.models.document.get_upload_path,
            ),
        ),
    ]
